# Generated by Django 4.0.6 on 2022-07-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0006_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='5bb7fa59d4564e21a6f051b0578ff1b9.jpg', null=True, upload_to=''),
        ),
    ]
