# Generated by Django 4.0.6 on 2022-07-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0009_alter_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
