# Generated by Django 4.0.6 on 2022-07-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0010_nurse_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
