# Generated by Django 4.0.6 on 2022-07-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0011_nurse_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='end_date_month',
            field=models.CharField(blank=True, choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April')], max_length=100, null=True),
        ),
    ]
