# Generated by Django 4.0.6 on 2022-07-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0012_alter_qualification_end_date_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='degree',
            field=models.CharField(blank=True, choices=[('Bsc Nursing', 'Bsc Nursing'), ('Bsc (Hons.) (Nursing)', 'Bsc (Hons.) (Nursing)'), ('Post Basic Bsc Nursing', 'Post Basic Bsc Nursing'), ('Bachelor of Science in Nursing(Post Certificate)', 'Bachelor of Science in Nursing(Post Certificate)'), ('A.N.M.', 'A.N.M.'), ('G.N.M.', 'G.N.M.'), ('Advanced Diploma in Ophthalmic Care Management', 'Advanced Diploma in Ophthalmic Care Management'), ('Diploma in Home Nursing', 'Diploma in Home Nursing'), ('Diploma in Emergency and Trauma Care Technician', 'Diploma in Emergency and Trauma Care Technician'), ('Diploma in Nursing Administraion', 'Diploma in Nursing Administraion'), ('Diploma in Neuro Nursing', 'Diploma in Neuro Nursing'), ('Diploma in Health Assistant(DHA)', 'Diploma in Health Assistant(DHA)'), ('Certificate course in Ayurvedic Nursing', 'Certificate course in Ayurvedic Nursing'), ('Certificate in Home Nursing', 'Certificate in Home Nursing'), ('Certificate in Maternal and Child Health Care(CMCHC)', 'Certificate in Maternal and Child Health Care(CMCHC)'), ('Certificate in Care Waste Management(CHCWM)', 'Certificate in Care Waste Management(CHCWM)'), ('Certificate in Primary Nursing Management(CPNM)', 'Certificate in Primary Nursing Management(CPNM)'), ('Msc Nursing', 'Msc Nursing'), ('Msc in Child Health Nursing', 'Msc in Child Health Nursing'), ('Msc in Community Health Nursing', 'Msc in Community Health Nursing'), ('Msc in Medical-Surgical Nursing', 'Msc in Medical-Surgical Nursing'), ('Msc in Maternity Nursing', 'Msc in Maternity Nursing'), ('Msc in Paediatric Nursing', 'Msc in Paediatric Nursing'), ('Msc in Obstetrics and Gyanecological Nursing', 'Msc in Obstetrics and Gyanecological Nursing'), ('Msc in Psychiatric Nursing', 'Msc in Psychiatric Nursing'), ('MD (Midwifery)', 'MD (Midwifery)'), ('PhD (Nursing)', 'PhD (Nursing)'), ('M Phil Nursing', 'M Phil Nursing'), ('Post Basic Diploma in Critical Care Nursing', 'Post Basic Diploma in Critical Care Nursing'), ('Post Basic Diploma in Orthopedic & Rehabilitation Nursing', 'Post Basic Diploma in Orthopedic & Rehabilitation Nursing'), ('Post Basic Diploma in Operation Room Nursing', 'Post Basic Diploma in Operation Room Nursing'), ('Post Graduate Diploma in paediatric Critical Care Nursing', 'Post Graduate Diploma in paediatric Critical Care Nursing'), ('Post Basic Diploma in Ontological Nursing and Rehabilitation Nursing', 'Post Basic Diploma in Ontological Nursing and Rehabilitation Nursing'), ('Post Gradute Diploma in Neo-Natal Nursing', 'Post Gradute Diploma in Neo-Natal Nursing'), ('Post Graduate Diploma in Emergency Nursing', 'Post Graduate Diploma in Emergency Nursing')], max_length=255, null=True),
        ),
    ]
