# Generated by Django 4.0.6 on 2022-07-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0014_user_isnurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='availability',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='convenience_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='verified',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='working_distance_in_kms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
