# Generated by Django 4.0.6 on 2022-07-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0015_alter_nurse_alternate_phone_alter_nurse_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
