# Generated by Django 4.0.6 on 2022-08-04 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0018_nurse_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='rating',
        ),
    ]
