# Generated by Django 4.0.6 on 2022-08-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0019_remove_nurse_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='nurse_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
